Importing my Libraries

In [0]:
import numpy as np
import pandas as pd

Making my Data Frame

In [4]:
df=pd.read_csv("http://bit.ly/Autolibdataset")
df.head()

   Unnamed: 0                     Address  Cars  ...  day  hour  minute
0           0              24 Rue Vulpian     3  ...    1     0       0
1           1  8 Boulevard Richard Lenoir     0  ...    1     0       0
2           2        4 Rue Charles Bossut     3  ...    1     0       0
3           3   3 avenue Claude Vellefaux     4  ...    1     0       0
4           4      236 Boulevard Voltaire     1  ...    1     0       0

[5 rows x 26 columns]

Validity

In [5]:
#Dropping some columns
df.drop(['Unnamed: 0','Address','ID','Geo point','minute','Displayed comment'], axis = 1 , inplace = True)
df.head()

   Cars  Bluecar counter  Utilib counter  ...  month  day hour
0     3                3               1  ...      4    1    0
1     0                0               0  ...      4    1    0
2     3                3               0  ...      4    1    0
3     4                4               0  ...      4    1    0
4     1                1               0  ...      4    1    0

[5 rows x 20 columns]

In [0]:
#We notice that the column names lack uniformity,we therefore change the names to lowercase.
df.columns=df.columns.str.lower()

In [7]:
df.columns

Index(['cars', 'bluecar counter', 'utilib counter', 'utilib 1.4 counter',
       'charge slots', 'charging status', 'city', 'kind', 'postal code',
       'public name', 'rental status', 'scheduled at', 'slots', 'station type',
       'status', 'subscription status', 'year', 'month', 'day', 'hour'],
      dtype='object')

In [9]:
#changing my "kind" column to lowecase for uniformity
df['kind'] = df['kind'].str.lower() 
df.head()

   cars  bluecar counter  utilib counter  ...  month  day hour
0     3                3               1  ...      4    1    0
1     0                0               0  ...      4    1    0
2     3                3               0  ...      4    1    0
3     4                4               0  ...      4    1    0
4     1                1               0  ...      4    1    0

[5 rows x 20 columns]

In [0]:
df.to_csv('cleaned_data')